memento:
  tech:
    backoffice:
      enabled: true
      media:
        enabled: true
        internal:
          file:
            storage:
              enabled: true
        mapping: /media
        file:
          import:
            upload:
              directory: ../media
      translation:
        enabled: true
        default:
          language: en
        useDefaultIfBlank: true
      auth:
        token:
          secret: 357638792F423F4428472B4B6250655368566D597133743677397A2443424567
        cookie:
          name: backofficeTokenCookie
          expiry: 31536000

debug: true

spring:
  h2:
    console.enabled: true
  mvc:
    view:
      prefix:
      suffix: .html
  profiles:
    active: igor-h2
  jpa:
    show-sql: false  # This enables the display of SQL queries in the logs
    properties:
      hibernate:
        search:
          backend:
            analysis:
              configurer: class:com.reserve.me.core.search.SearchConfiguration
            directory:
              root: ../indexes
            type: lucene
        hbm2ddl:
          import_files_sql_extractor: org.hibernate.tool.schema.internal.script.MultiLineSqlScriptExtractor
        format_sql: false  # This formats the SQL queries for better readability
    #        use_sql_comments: true  # This adds comments to SQL queries for better context
    #        generate_statistics: true  # Useful for additional statistics in logs
    logging:
      level:
        org:
          hibernate:
            SQL: debug  # This shows the SQL queries being executed
            type:
              descriptor:
                sql:
                  BasicBinder: debug # This logs the values of the parameters being passed